spring.datasource.url=jdbc:postgresql://localhost:5432/ong
spring.datasource.username=postgres
spring.datasource.password=02092020

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.override-with-generic-response=false



spring.application.name=Ong
